[package]
name = "rust-test"
version = "0.1.0"
authors = ["tarkah <admin@tarkah.dev>"]
edition = "2018"


[dependencies]
tokio = { version = "0.2", features = ["macros"] }
lambda_http = { git = "https://github.com/awslabs/aws-lambda-rust-runtime/", branch = "master"}
serde_json = "1.0"

serde = { version = "1.0", features = ["derive"] }
log = "0.4"
simple_logger = "1.11"
rusoto_rds_data= "0.45.0"
rusoto_signature = "0.45.0"